### ISSUE TITLE
Key error from new_XStringSet_from_CHARACTER call

### ISSUE THREAD

**Issue by morien** [Bioconductor/Biostrings#47]
I'm hoping for some help debugging this issue. It's the same error as this previous issue: https://github.com/Bioconductor/Biostrings/issues/35
However the character "1" which is said to throw the error is not in my DNA sequences, I have confirmed several times over with various grep commands. The only characters in my DNA sequences are ACTG, N, and a few degenerate bases.

Here is the error: 
```
Error in .Call2("new_XStringSet_from_CHARACTER", class(x0), elementType(x0),  : 
  key 49 (char '1') not in lookup table
```
Here is the command (yes, this is from dada2 assignTaxonomy function, but I am asking here because it's the biostrings function call that's throwing the error, even some clarity that the problem is upstream will help me, if that is the case): 
`taxa <- assignTaxonomy(seqtab, "COI_reference_dada2gen.fa.gz", multithread=TRUE, verbose=TRUE)`

Here is a snippet of the input fasta file:
```
>Eukaryota;Metazoa;Arthropoda;Insecta;Coleoptera;Coccinellidae;Epilachna;Epilachna admirabilis;AB002178|77537;
CGCCTTTATCAGCAAATATTGCTCATGGA...
>Eukaryota;Metazoa;Arthropoda;Insecta;Coleoptera;Coccinellidae;Epilachna;Epilachna sp. H;AB002179|77538;
AGCAAATATCGCACATGGAGGATCATCTG...
>Eukaryota;Metazoa;Arthropoda;Insecta;Coleoptera;Coccinellidae;Henosepilachna;Henosepilachna vigintioctopunctata;AB002180|420089;
AGTTTACCCACCTCTTTCAGCTAATATTG...
>Eukaryota;Metazoa;Arthropoda;Insecta;Coleoptera;Coccinellidae;Henosepilachna;Henosepilachna vigintioctopunctata;AB002181|420089;
AGTTTACCCTCCTCTTTCAGCTAATATTG...
```
A grep to find any errant numbers in the fasta sequence yields nothing:
`grep '[0-9]' COI_reference_dada2gen.fa | grep -v ">"
`

Please note all sequences begin and end with [ACTG] or degenerate bases, I've truncated them in the example to make this post easier to read.

Thanks in advance for any guidance anyone can provide.

**Comment by hpages** [comment]
Hi,

So where is the `COI_reference_dada2gen.fa.gz` file so we can actually try to reproduce your problem?

Otherwise we're just going to have to take your word that the file doesn't contain the `1` character, and you're just going to have to take my word that there's no way that the `DNAStringSet()` or `DNAString()` constructors would raise this kind of error if all the characters in their input belong to the `DNA_ALPHABET`. But then in the middle of that there's the `assignTaxonomy()` function from the **dada2** package that could be doing all kinds of strange things.

So like for issue #35, or any bug report in general, you need to provide a reproducible example, that is, show us some short code snippet that is self-contained so we can just copy-and-paste it in our R session to reproduce the problem. Also please provide your `sessionInfo()`.

Alternatively you may want to ask on the Bioconductor support site: https://support.bioconductor.org/ You will reach to a much larger audience there. If you do so please make sure to read our Posting Guide before posting your question. In particular make sure to tag your question appropriately and to provide a minimum reproducible example and `sessionInfo()`.

Thanks!

**Comment by morien** [comment]
Apologies, I should have closed this earlier but it fell off my radar. A few days after posting I was able to trace the error to a separate call of DNAStringSet (rather than the one for the fasta file I was focused on above). A dada2 function upstream of yours was passing a non DNA character to DNAStringSet, due to a problem with the other (non-fasta) input file.
