### ISSUE TITLE
confused about reading in a single long fasta subject sequence for pattern matching

### ISSUE THREAD

**Issue by tchrisboles** [Bioconductor/Biostrings#89]
I want to search for crRNA matches along a single subject sequence. 
I thought it was required that I use readDNAStringSet() to import sequences from fasta files. 
However, when I run matchPDict using the imported subject I get an error that says I should have used vmatchPDict() (which is not ready).
How should I import my single large subject file (~5Mb)?

![image](https://user-images.githubusercontent.com/33500125/206809265-a7f98f6f-6103-4591-8fa8-4a1f81752ff0.png)

**Comment by hpages** [comment]
Using a screenshot when you can simply copy-paste the content of your terminal in the issue is really not a good idea. This will prevent others from finding this issue when they search issues by function name (e.g. `matchPDict`). It will also prevent the people who are trying to help you from copy-past'ing your code when they try to reproduce the problem on their own machine.

As for your problem: Please make sure to consult the man page for `matchPDict()`. There it clearly says that `matchPDict()` expects the `subject` to be a DNAString object. In your case, `hap` is a DNAStringSet object of length 1. DNAStringSet objects are list-like objects where the list elements are DNAString objects. To extract the first and sole list element from `hap`, just do `hap[[1]]`. This will return the first and sole list element in `hap` as a DNAString object.

Hope this helps,
H.

**Comment by hpages** [comment]
Finally note that questions about how to use the software are generally better asked on our support site [here](https://support.bioconductor.org). GitHub issues should preferrably be used for reporting bugs and other issues with the software, or for requesting new features. Thanks!

H.

**Comment by tchrisboles** [comment]
Thanks for your reply.

Sorry for the bad etiquette.

Best regards,

Chris Boles, Ph.D, Chief Scientific Officer
Sage Science, Inc., 500 Cummings Center, Suite 2400, Beverly, MA 01915
Direct Office: +1-978-522-6284, Mobile: +1-781-856-2165
Company: +1-978-922-1832
***@***.***

This e-mail may contain information that is confidential or privileged. If
you are not the intended recipient, do not read, copy or distribute the
e-mail or any attachments. Instead, please notify the sender and delete the
e-mail and any attachments. Thank you.

**Comment by tchrisboles** [comment]
Thanks again.
Again, sorry for the bad etiquette.

Best regards,

Chris Boles, Ph.D, Chief Scientific Officer
Sage Science, Inc., 500 Cummings Center, Suite 2400, Beverly, MA 01915
Direct Office: +1-978-522-6284, Mobile: +1-781-856-2165
Company: +1-978-922-1832
***@***.***

This e-mail may contain information that is confidential or privileged. If
you are not the intended recipient, do not read, copy or distribute the
e-mail or any attachments. Instead, please notify the sender and delete the
e-mail and any attachments. Thank you.
